FROM artifacts.msap.io/mulesoft/core-paas-base-image-node-18:v4.7.40

ENV FIPS_ENABLED=false

WORKDIR /usr/src/app

USER root

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

COPY . .

RUN chown -R app:app . \
    && npm ci

USER app
RUN npx gulp bundle
