= Access Management
:page-component-name: access-management
:keywords: anypoint platform, permissions, configuring

Use *Anypoint Access Management* to create your Anypoint Platform account or configure federated External Identity.

TIP: Account creation and user invitation from the platform is not available for Anypoint Platform Private Cloud Edition.
Users running Anypoint Platform Private Cloud Edition need to define a method to manage users.

Additionally, you can configure access and permissions within your Organization and, based on your access level, manage the Users and Roles.

NOTE: As of November 2014, accounts in both the Anypoint Platform for APIs and CloudHub have been merged. For more information about what this merging of accounts implies and how it's being handled, read Upcoming Changes to Anypoint Platform Accounts.

If you have any questions about your account, contact your MuleSoft Account Team for assistance.

Anypoint Access Management also provides a REST API for you to programmatically access the resources related to user and client management, organizations and business groups, and roles and permissions.
Check the https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/11270/versions/11646/pages/11244[Access Management API Portal].
