= MuleSoft Documentation
:linkattrs:
:experimental:

Use Anypoint Platform to build a structured application network that connects applications, data, and devices with reusable APIs.

== Explore Anypoint Exchange

The APIs you build in MuleSoft to integrate applications and services are, by design, reusable and built with enterprise security in mind.
You can discover these APIs, as well as connectors, samples, and templates in
https://www.anypoint.mulesoft.com/exchange/[Exchange^].

RAML fragments, custom packages, videos, links to documentation, and other assets are also available.

== Design and Build Integrations

Anypoint Studio is an Eclipse-based IDE that helps you create Mule apps and APIs, and Design Center is the cloud-based tool.

|===
| Creating Mule Apps | Creating APIs

| link:#[Building Mule Apps in Anypoint Studio] | link:#[Importing APIs from Design Center to Anypoint Studio]
| link:#[Building Apps in Design Center]  | link:#[Creating APIs in Design Center]
|===

Studio 7 includes link:#[Mule Runtime (Mule) 4], the runtime environment where you deploy Mule apps and APIs.
Earlier versions of Studio include link:#[Mule 3].

|===
| Mule 3 | Mule 4

| link:#[Connectors for Mule 3] | link:#[Connectors for Mule 4]
| link:#[DataWeave 1 for Mule 3]  | link:#[DataWeave 2 for Mule 4]
| link:#[APIkit 3] | link:#[APIkit 4]
| link:#[Connector DevKit] | link:#[Mule SDKs]
|===

You can test and run the apps and APIs you build from Studio or Design Center.

== Deploy Integrations

* link:#[Choosing a deployment strategy]
* link:#[Installing Standalone Mule 3]
* link:#[Installing Standalone Mule 4]

== Test Integrations

* link:#[Testing with MUnit]
* link:#[Troubleshooting]

== Manage Integrations

* link:#[Anypoint Monitoring]
* link:#[API Functional Monitoring]
* link:#[Runtime Monitoring]

== Manage Anypoint Platform Features

* link:#[Design Center]
* link:#[API Manager]
* link:#[Access Management]

== More Resources

* link:#[Release Notes]
* http://developer.mulesoft.com[MuleSoft developer site^]
* https://training.mulesoft.com/[Training^]

== Contributing to the Documentation

To contribute to this documentation, select btn:[Edit in Github] on the page you wish to modify, and submit a pull request to the git repo.
Your improvements to MuleSoft documentation are appreciated by the entire community.
Thank you!

== Archived Documentation

When an older version of a product is no longer supported, including products with end-of-life status, the documentation moves to an https://docs.archive.mulesoft.com/[archive site^].
