= Welcome to the preview site!
:keywords: preview, previewing, preview site
:experimental:
:page-component-name: connector-devkit
:page-version: 3.8

This is the preview site. Before you make any changes, please make sure that the elements are displaying correctly.

For example, link:/connectors.html[Anypoint Connectors] should take you to the connectors page.

TIP: This is the index.adoc in the repo, if you need to edit it further.

== Where is everything?

The left navigation pane tells you what each section is about.

* *Home* contains a few more realistic pages, as well as an external link.
* *Elements* are where you verify that the various elements (e.g. tables, code blocks) are rendering correctly.
* *Test nav header* tests that the headers are rendering correctly - versions, parent-child relationships, etc. All the pages are unclickable here
* *Data Gateway* represents a more realistic section of the site, except that all the images are broken.
* *Connectors* tests the connector pages. The connectors home is notably different than all other pages, and the individual connector pages are a little different as well.

== How may I perform a thorough validation?

[NOTE]
====
Even though it is not required to perform a thorough validation every time you make changes, it is recommended that you should click around to make sure that your changes are not accidentally breaking elements of the site, especially if the changes are done in CSS and JavaScript.
====

=== Header and footer

[%interactive]
* [ ] The header is at the top of the page and is clickable. All links are working
* [ ] The footer is at the bottom of the page and is clickable. All links are working

=== Left-hand navigation

[%interactive]
* [ ] A list of links should be visible and clickable (to take you to a different page).
* [ ] The version dropdown should be visible and clickable.

=== Right-hand navigation (TOC)

[%interactive]
* [ ] A list of links should be visible and clickable (to take you to the corresponding header).
* [ ] In most of the pages (except for 404 page, connectors home page, etc.), you can see the "Edit on Github" link at the top, even though they lead to 404 pages.

== Preview Site Limitations

While the preview site is great for quick testing, it has the following limitations:

* The left navigation pane doesn't keep the headers expanded for the page you are viewing
* Can't use partials

To get around it, run `gulp bundle` to create a zip file, then test building it in antora-playbook. See the readme for further instructions.

== What's next?

Click around and find out! Everything that doesn't say that it's not clickable are, well, clickable. Have fun!
