= Welcome to the preview site!
:keywords: preview, previewing, preview site
:experimental:

This is the preview site. Before you make any changes, please make sure that the elements are displaying correctly.

For example, link:/connectors.html[Anypoint Connectors] should take you to the connectors page.

If you need to edit this page, this is the index.adoc in the repo.

== How may I perform a thorough validation?

[NOTE]
====
It's nice to perform a thorough validation, but it's not required, as long as you can validate the parts you have changed.
====

=== Left-hand navigation

[%interactive]
* [ ] A list of links should be visible and clickable (to take you to a different page).
* [ ] The version dropdown should be visible and clickable.

=== Right-hand navigation (TOC)

[%interactive]
* [ ] A list of links should be visible and clickable (to take you to the corresponding header).
* [ ] The survey banner should be visible at the bottom and is clickable.
* [ ] Adjust the width of the window - the survey banner should be moved to the bottom of the page.

== Preview Site Limitations

The preview site is great for quick testing, but has the following limitations:

* The left navigation pane doesn't keep the headers expanded for the page you are viewing
* Can't use partials

To get around it, run `gulp bundle` to create a zip file, then test building it in antora-playbook. See the readme for further instructions.

== What's next?

Click around and find out! Have fun!