= 使用状況レポートの表示
:page-aliases: gateway::flex-view-usage-reports.adoc

使用状況レポートは、毎月の Anypoint Platform 製品の使用状況に関するインサイトを提供します。 

[NOTE]
--
使用状況レポートを参考にして、実際の使用量を既存の契約と比較してください。このレポートは請求を目的としたものではありません。 
--

== 使用状況レポートの概要

Anypoint Platform 製品を使用すると、MuleSoft は使用量を測定して、毎月レコードを集計します。使用状況レポートは、毎月 3 日に更新され、製品ごとに分割されます。すべてのレポートは UTC 時間標準を使用して計算されます。

使用状況レポートは、次の Anypoint Platform 製品で用意されています。

=== Flex Gateway

Flex Gateway の使用状況レポートは、毎月の API コール数を追跡します。毎月の API コール数は、ビジネスグループ、環境、登録ごとに表示できます。

使用量の計算では、MuleSoft は毎時の API コール数を測定して、毎月の API コール数を集計します。 

=== API Governance

API Governance の使用状況レポートは、特定の月においてビジネスグループごとに​xref:api-governance::index.adoc#governed-apis[管理された API]​ の最大数を追跡します。 

使用量の計算では、MuleSoft は、各ビジネスグループが毎時使用した管理された API 数を追跡して、ビジネスグループごとの 1 か月間の管理された API の最大数を特定します。API Governance の合計数の計算では、MuleSoft はすべてのビジネスグループで使用される管理された API の最大数を加算します。 

API Governance コンソールに表示される管理された API (準拠および非準拠の両方) の数は、ビジネスグループごとの現時点での使用状況のスナップショットを表しています。一方で使用状況レポートは、特定の月において使用された API のビジネスグループごとの最大数を示します。

=== API Manager

API Manager の使用状況レポートは、特定の月においてビジネスグループ、環境、およびランタイムごとにデプロイされた ​xref:api-manager::latest-overview-concept.adoc#api-instances[API インスタンス]​の最大数を追跡します。 

使用量の計算では、MuleSoft は、各ビジネスグループ、環境、およびランタイムが毎時使用した管理された API インスタンス数を追跡して、ビジネスグループ、環境、およびランタイムごとのが 1 か月間に使用される管理された API インスタンスの最大数を特定します。API Manager の合計数の計算では、MuleSoft はビジネスグループ、環境、およびランタイムで使用される 1 か月ごとの管理された API インスタンスの最大数を加算します。

=== Mule Runtime

ランタイムレポートでは、Mule メッセージ、Mule フロー、データスループットの使用を追跡します。 

Mule メッセージの使用状況を追跡するために、レポートでは Mule イベントソースが Mule メッセージをトリガする回数を数えます。特定の月のこれらのメッセージの数は、ビジネスグループ、環境、およびアプリケーション別に参照できます。使用量の計算では、MuleSoft は 1 か月ごとのメッセージ数を測定して集計します。メッセージがトリガされると、レポートではメッセージに対する変更が追跡されなくなります。これは、変更がアプリケーションのフロー内で処理されるためです。

Mule フローは Mule アプリケーションの XML <flow/> 要素内で設定される論理操作のシーケンスです。レポートでは、Mule イベントソースまたはルート APIKit 要求が含まれるデプロイ済みおよび実行中の Mule アプリケーション内の Mule フローを追跡します。このレポートでは、他の Mule フローは追跡しません。特定の月の Mule フローの最大数は、使用状況レポートで参照できます。使用量の計算では、MuleSoft は、すべてのビジネスグループ、環境、アプリケーションの Mule フロー数を追跡します。1 か月間の Mule フローの最大数はその月のピーク時間に基づいて特定されます。詳細な内訳を確認できるように、MuleSoft ではビジネスグループ、環境、アプリケーションごとのピーク時間の使用量が表示されます。 

データスループットとは、Mule アプリケーションを実行する Mule Runtime Engine を起動および実行するインフラストラクチャによって生成されたすべてのネットワーク I/O バイトを指します。特定の月の GB 使用量の合計数は、ビジネスグループ、環境、およびアプリケーション別に参照できます。使用量の計算では、MuleSoft は GB 使用量を追跡して 1 か月ごとの追跡対象 Mule メッセージ数を集計します。

[NOTE]
--
このレポートには、アプリケーションおよび環境の ID がリストされます。 
--

== 使用状況レポートにアクセスする

使用状況レポートにアクセスするには、Access Management で「Usage Viewer (使用状況閲覧者)」権限を持っている必要があります。

. Anypoint Platform ナビゲーションバーで、自分のユーザ名アイコンをクリックします。
. *[Usage (使用状況)]*​ をクリックします。
. 特定の月のレポートを表示するには、​*[Monthly Usage Reports (月次使用状況レポート)]*​ ドロップダウンリストをクリックします。


== 関連情報

* xref:gateway::flex-gateway-getting-started.adoc[]
* xref:api-governance::index.adoc[]
* xref:api-manager::index.adoc[]
