name: Hello World

on:
  push:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: mulesoft-ubuntu
    
    steps:
    - name: Print Hello World
      run: echo "Hello World"
